/**
 * @description       : 
 * @author            : otto.virtanen@ceili.fi
 * @group             : 
 * @last modified on  : 06-29-2022
 * @last modified by  : otto.virtanen@ceili.fi
**/
public with sharing class DemoClass {
    /**
    * @description 
    * @author otto.virtanen@ceili.fi | 06-29-2022 
    **/
    public static void debug() {
        System.debug('Kissa istuu puussa');
        System.debug('Something changed');
    }
}